import { describe, it, expect } from 'vitest';
import { extractSessionName, extractRenamedTitle } from '../nameExtractor';

// Regression: a recent Claude Code update records slash-command scaffolding as the first
// `type:"user"` turns — an `isMeta:true` <local-command-caveat> block, then <command-name>/
// <command-message>/<command-args> blocks, then <local-command-stdout>. The extractor used to
// grab the first text block, so EVERY session opened with a slash command (/model, /clear, …)
// got the identical title "<local-command-caveat>Caveat…". Identical titles collapse two
// genuinely distinct concurrent sessions on the same project+branch into one dedupe slot —
// "two sessions running, extension shows only one". The extractor must skip scaffolding and
// return the first real user prompt.

const caveat = {
  type: 'user',
  isMeta: true,
  message: {
    role: 'user',
    content:
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
  },
};

const commandBlock = {
  type: 'user',
  message: {
    role: 'user',
    content:
      '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>',
  },
};

const commandStdout = {
  type: 'user',
  message: { role: 'user', content: '<local-command-stdout>Set model to claude-opus-4-8</local-command-stdout>' },
};

const taskNotification = {
  type: 'user',
  message: { role: 'user', content: '<task-notification>\n<task-id>abc</task-id>\n</task-notification>' },
};

const realPrompt = {
  type: 'user',
  message: { role: 'user', content: 'qual worktree você esta ?' },
};

describe('extractSessionName — slash-command scaffolding', () => {
  it('skips the isMeta caveat block', () => {
    expect(extractSessionName(caveat)).toBeNull();
  });
  it('skips <command-*> scaffolding blocks', () => {
    expect(extractSessionName(commandBlock)).toBeNull();
  });
  it('skips <local-command-stdout> blocks', () => {
    expect(extractSessionName(commandStdout)).toBeNull();
  });
  it('skips <task-notification> blocks', () => {
    expect(extractSessionName(taskNotification)).toBeNull();
  });
  it('returns the real user prompt', () => {
    expect(extractSessionName(realPrompt)).toBe('qual worktree você esta ?');
  });
});

// Regression: Claude Code 2.1.223 auto-stamps a `type:"custom-title"` entry equal to the
// session's own git-worktree name every time a session enters that worktree — the same entry
// type this extractor otherwise treats as an explicit, permanent user rename. Trusting it made
// every session that ever entered a given worktree collapse onto the identical sessionTitle, so
// sessionDedupe.getDedupeKey() (keyed on type+projectPath+gitBranch+title) collided them onto one
// slot — silently dropping every session but the isMoreRelevant winner, including the one
// actively running subagents. Real capture (structured-logging worktree, four independent
// sessions, four different real prompts, one identical stamped title): `{"type":"custom-title",
// "customTitle":"structured-logging",...}`. Mirrors the SCAFFOLD_PREFIXES precedent above — same
// class of "don't trust it just because it arrived as a custom-title entry" problem, different
// trigger.
describe('extractRenamedTitle — auto-stamped worktree label', () => {
  it('accepts a real user rename', () => {
    expect(extractRenamedTitle({ type: 'custom-title', customTitle: 'Auth spike' })).toBe('Auth spike');
  });

  it("rejects an auto-stamped custom-title that exactly matches the session's own worktree name", () => {
    expect(
      extractRenamedTitle({ type: 'custom-title', customTitle: 'structured-logging' }, 'structured-logging'),
    ).toBeNull();
  });

  // Regression (code-reviewer HIGH finding on the fix above): Claude Code substitutes `/` with
  // `+` when it stamps a slash-containing worktree name into customTitle — real capture, two
  // unrelated sessions on this machine: `worktreeName:"feat/42-example-generic-feature-
  // name"` stamped as `customTitle:"feat+42-example-generic-feature-name"`, and
  // `worktreeName:"fix/17-another-example-branch-name"` stamped as
  // `customTitle:"fix+17-another-example-branch-name"`. A raw `===` check (the first
  // pass at this fix) never recognized these as the auto-stamp, reopening the exact collision
  // this function exists to close for any slash-containing worktree name — the mainstream case
  // for `feature/…`/`fix/…`/`chore/…`-derived worktrees.
  it('rejects an auto-stamped custom-title even when Claude Code substituted "/" with "+" in it', () => {
    expect(
      extractRenamedTitle(
        { type: 'custom-title', customTitle: 'feat+42-example-generic-feature-name' },
        'feat/42-example-generic-feature-name',
      ),
    ).toBeNull();
    expect(
      extractRenamedTitle(
        { type: 'custom-title', customTitle: 'fix+17-another-example-branch-name' },
        'fix/17-another-example-branch-name',
      ),
    ).toBeNull();
  });

  it('still accepts a custom-title that differs from the known worktree name', () => {
    expect(extractRenamedTitle({ type: 'custom-title', customTitle: 'Auth spike' }, 'structured-logging')).toBe(
      'Auth spike',
    );
  });

  it('accepts the custom-title unchanged when no worktree name is known yet', () => {
    expect(extractRenamedTitle({ type: 'custom-title', customTitle: 'structured-logging' })).toBe('structured-logging');
  });

  // Regression: Claude Code's auto-stamp for a NESTED worktree path (this project's own
  // `.claude/worktrees/<type>/<slug>` convention) is observed to sometimes capture only the
  // FIRST `/`-segment of the worktree name, not the full name — even when a worktree-state entry
  // on the same transcript already recorded the full name. Real capture: session on branch
  // `feat/787-saque-de-brl-via-pix-mvp-fluxo-3-fases-t`, worktree-state recorded the full
  // `worktreeName:"feat/787-saque-de-brl-via-pix-mvp-fluxo-3-fases-t"`, yet the very next
  // custom-title auto-stamp was just `"feat"`. The pre-existing full-string (mod `/`→`+`)
  // comparison above missed this shape entirely, so the truncated stamp slipped through as a
  // "real rename" and overwrote an already-correct, prompt-derived title.
  it('rejects an auto-stamped custom-title that matches only the first segment of a nested known worktree name', () => {
    expect(
      extractRenamedTitle(
        { type: 'custom-title', customTitle: 'feat' },
        'feat/787-saque-de-brl-via-pix-mvp-fluxo-3-fases-t',
      ),
    ).toBeNull();
  });

  it('still accepts a custom-title matching neither the full nor the first-segment known worktree name', () => {
    expect(
      extractRenamedTitle(
        { type: 'custom-title', customTitle: 'saque' },
        'feat/787-saque-de-brl-via-pix-mvp-fluxo-3-fases-t',
      ),
    ).toBe('saque');
  });

  it('does not use the segment fallback when the known worktree name has no "/" (first segment would equal the whole name)', () => {
    expect(extractRenamedTitle({ type: 'custom-title', customTitle: 'feat' }, 'structured-logging')).toBe('feat');
  });
});
