import { describe, it, expect } from 'vitest';
import { extractSessionName } from '../nameExtractor';

// Regression: a recent Claude Code update records slash-command scaffolding as the first
// `type:"user"` turns — an `isMeta:true` <local-command-caveat> block, then <command-name>/
// <command-message>/<command-args> blocks, then <local-command-stdout>. The extractor used to
// grab the first text block, so EVERY session opened with a slash command (/model, /clear, …)
// got the identical title "<local-command-caveat>Caveat…". Identical titles collapse two
// genuinely distinct concurrent sessions on the same project+branch into one dedupe slot —
// "two sessions running, extension shows only one". The extractor must skip scaffolding and
// return the first real user prompt.

const caveat = {
  type: 'user',
  isMeta: true,
  message: {
    role: 'user',
    content:
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
  },
};

const commandBlock = {
  type: 'user',
  message: {
    role: 'user',
    content:
      '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>',
  },
};

const commandStdout = {
  type: 'user',
  message: { role: 'user', content: '<local-command-stdout>Set model to claude-opus-4-8</local-command-stdout>' },
};

const taskNotification = {
  type: 'user',
  message: { role: 'user', content: '<task-notification>\n<task-id>abc</task-id>\n</task-notification>' },
};

const realPrompt = {
  type: 'user',
  message: { role: 'user', content: 'qual worktree você esta ?' },
};

describe('extractSessionName — slash-command scaffolding', () => {
  it('skips the isMeta caveat block', () => {
    expect(extractSessionName(caveat)).toBeNull();
  });
  it('skips <command-*> scaffolding blocks', () => {
    expect(extractSessionName(commandBlock)).toBeNull();
  });
  it('skips <local-command-stdout> blocks', () => {
    expect(extractSessionName(commandStdout)).toBeNull();
  });
  it('skips <task-notification> blocks', () => {
    expect(extractSessionName(taskNotification)).toBeNull();
  });
  it('returns the real user prompt', () => {
    expect(extractSessionName(realPrompt)).toBe('qual worktree você esta ?');
  });
});
