import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { LogParser, LogEntry } from '../logParser';
import { detectSubagents } from '../subagentDetector';
import { SubAgent } from '../types';

/**
 * Golden-master regression test for the tolerant-reader parser (LogParser + detectSubagents)
 * against src/test/fixtures/schema-corpus/: up to 3 redacted real sample lines per observed
 * transcript `type`(:`subtype`) bucket, generated by this project's dev-time-only
 * scripts/schema-gen/ tool (see transcript-schema-gen.md; never imported from here — that tree
 * sits outside the src/ TS project on purpose).
 *
 * Unlike real-logs/'s fixtures (full multi-turn sessions built around one specific bug), these
 * are single-line-per-bucket samples spanning many distinct `type` values, so the bulk of the
 * per-type shape capture leans on Vitest's own snapshot mechanism instead of hand-written field
 * assertions per bucket: if the tolerant reader silently stops reading a field, or a `type` that
 * used to render now gets silently dropped, the parsed shape changes and the snapshot diff fails
 * on the next run.
 *
 * Two Session fields are normalized to a fixed marker before snapshotting — not because they're
 * untested, but because they are inherently environment-dependent:
 *  - `logFilePath` is the absolute path passed to LogParser.parse() — differs by checkout
 *    location (this machine vs. any other clone), so snapshotting it verbatim would both fail to
 *    reproduce elsewhere and bake this developer's absolute path into a committed file.
 *  - `lastInteractionTime` falls back to the fixture file's on-disk mtime (parseTimestamp in
 *    logParser.ts) whenever a line carries no timestamp/time/created field — true for several
 *    buckets here (e.g. mode, custom-title, ai-title) — and mtime changes on every fresh
 *    checkout/clone, which would make the suite fail outside this one machine.
 * Both are still shape-checked with a real assertion right before normalization.
 */
const FIXTURES_DIR = path.join(__dirname, 'fixtures', 'schema-corpus');
const bucketFiles = fs
  .readdirSync(FIXTURES_DIR)
  .filter((file) => file.endsWith('.jsonl'))
  .sort();

const NORMALIZED_PATH = '<fixture-path-normalized-for-portability>';
const NORMALIZED_TIMESTAMP = '<timestamp-normalized-for-determinism>';
const NORMALIZED_ID = '<subagent-id-normalized-for-determinism>';

function readSampleLines(filePath: string): string[] {
  return fs
    .readFileSync(filePath, 'utf8')
    .split('\n')
    .filter((line) => line.trim().length > 0);
}

describe('Schema golden master (schema-corpus fixtures)', () => {
  it('discovered committed fixture buckets under schema-corpus/', () => {
    // If this fails, the loop below registered zero per-bucket tests — every other check in this
    // file "passing" would be vacuous, not a real regression guarantee.
    expect(bucketFiles.length).toBeGreaterThan(0);
  });

  for (const file of bucketFiles) {
    const bucketName = file.replace(/\.jsonl$/, '');
    const filePath = path.join(FIXTURES_DIR, file);
    const rawLines = readSampleLines(filePath);

    it(`${bucketName}: LogParser.parse() produces a stable session shape`, () => {
      expect(rawLines.length).toBeGreaterThan(0);

      // claudeProjectsPath anchored at FIXTURES_DIR itself (LogParser's constructor accepts this
      // for exactly this purpose — see logParser.projectPath.test.ts) so the derived
      // projectHash/projectName come from the fixture's own relative filename, not this
      // machine's real home-directory layout.
      const parser = new LogParser(FIXTURES_DIR);
      const session = parser.parse(filePath, 'claude-code');

      expect(path.basename(session.logFilePath)).toBe(file);
      expect(typeof session.lastInteractionTime).toBe('number');

      expect({
        ...session,
        logFilePath: NORMALIZED_PATH,
        lastInteractionTime: NORMALIZED_TIMESTAMP,
      }).toMatchSnapshot();
    });

    it(`${bucketName}: detectSubagents() runs against every sample line without throwing`, () => {
      expect(rawLines.length).toBeGreaterThan(0);

      // Called directly (not just via LogParser.parse() above) because LogParser.parse() wraps
      // its ENTIRE pipeline in a try/catch that silently returns an empty session on any thrown
      // error (logParser.ts's documented "parsing never throws" contract) — a future regression
      // that made detectSubagents throw on some shape would be swallowed there and never show up
      // as a distinct failure. Calling it unwrapped is the only way this suite catches that.
      const currentSubagents = new Map<string, SubAgent>();
      for (const line of rawLines) {
        const json = JSON.parse(line) as LogEntry;
        expect(() => {
          detectSubagents(json, currentSubagents);
        }).not.toThrow();
      }

      // `id` can fall back to Math.random().toString() when a matched block carries no id of its
      // own (see subagentDetector.ts) — normalized for the same determinism reason as the two
      // Session fields above; every other field reflects real, redacted-but-structural data.
      const subagents = Array.from(currentSubagents.values()).map((sub) => ({ ...sub, id: NORMALIZED_ID }));
      expect(subagents).toMatchSnapshot();
    });
  }
});
